spring:
  datasource:
    url: jdbc:mysql://106.75.143.161:3306/sso_new?characterEncoding=utf-8
    username: root
    password: mysql.123
    driver-class-name: com.mysql.jdbc.Driver
demo:
  conf:
    elasticsearch:
      ip: 10.0.2.103:9200,10.0.2.103:9210,10.0.2.103:9220